### ISSUE TITLE
Doesn't appear to support stand-alone tomcat ?

### ISSUE THREAD

**Issue by 4ULjPwGBOC33N** [AcuGIS/Tomcat-Webmin-Module#1]
Hi,
installed successfully into webmin 1.910 on Ubuntu 16.04 LTS with Tomcat8. When trying to configure module it assumes I am going to use apache2 as a proxy and asks to install it. I am running a stand-alone tomcat. Is it possible to disable the assumption that apache is required ?

**Comment by DavidGhedini** [comment]
Hi -
You can opt out of installing any unwanted components by simply clicking the "if no further errors..." button to complete installation.
Ill add that to the documentation to make it more explicit.

**Comment by 4ULjPwGBOC33N** [comment]
Thank-you, perfect ! Much appreciated.
